export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  UPLOAD_REQUEST: "UPLOAD_REQUEST",
  UPLOAD_FAILURE: "UPLOAD_FAILURE",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const categoryConstansts = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};

export const courseConstants = {
  GET_ALL_COURSES_REQUEST: "GET_ALL_COURSES_REQUEST",
  GET_ALL_COURSES_SUCCESS: "GET_ALL_COURSES_SUCCESS",
  GET_ALL_COURSES_FAILURE: "GET_ALL_COURSES_FAILURE",

  GET_ALL_COURSES_PUBLISHED_REQUEST: "GET_ALL_COURSES_PUBLISHED_REQUEST",
  GET_ALL_COURSES_PUBLISHED_SUCCESS: "GET_ALL_COURSES_PUBLISHED_SUCCESS",
  GET_ALL_COURSES_PUBLISHED_FAILURE: "GET_ALL_COURSES_PUBLISHED_FAILURE",

  DELETE_COURSE_BY_ID_REQUEST: "DELETE_COURSE_BY_ID_REQUEST",
  DELETE_COURSE_BY_ID_SUCCESS: "DELETE_COURSE_BY_ID_SUCCESS",
  DELETE_COURSE_BY_ID_FAILURE: "DELETE_COURSE_BY_ID_FAILURE",

  ADD_COURSE_REQUEST: "ADD_COURSE_REQUEST",
  ADD_COURSE_SUCCESS: "ADD_COURSE_REQUEST",
  ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",

  UPDATE_COURSES_REQUEST: "UPDATE_COURSES_REQUEST",
  UPDATE_COURSES_SUCCESS: "UPDATE_COURSES_SUCCESS",
  UPDATE_COURSES_FAILURE: "UPDATE_COURSES_FAILURE",
};

export const curriculumConstants = {
  GET_ALL_CURRICULUMS_REQUEST: "GET_ALL_CURRICULUMS_REQUEST",
  GET_ALL_CURRICULUMS_SUCCESS: "GET_ALL_CURRICULUMS_SUCCESS",
  GET_ALL_CURRICULUMS_FAILURE: "GET_ALL_CURRICULUMS_FAILURE",

  GET_ONE_CURRICULUMS_REQUEST: "GET_ONE_CURRICULUMS_REQUEST",
  GET_ONE_CURRICULUMS_SUCCESS: "GET_ONE_CURRICULUMS_SUCCESS",
  GET_ONE_CURRICULUMS_FAILURE: "GET_ONE_CURRICULUMS_FAILURE",

  GET_ALL_CURRICULUMS_PUBLISHED_REQUEST: "GET_ALL_CURRICULUMS_PUBLISHED_REQUEST",
  GET_ALL_CURRICULUMS_PUBLISHED_SUCCESS: "GET_ALL_CURRICULUMS_PUBLISHED_SUCCESS",
  GET_ALL_CURRICULUMS_PUBLISHED_FAILURE: "GET_ALL_CURRICULUMS_PUBLISHED_FAILURE",

  DELETE_CURRICULUM_BY_ID_REQUEST: "DELETE_CURRICULUM_BY_ID_REQUEST",
  DELETE_CURRICULUM_BY_ID_SUCCESS: "DELETE_CURRICULUM_BY_ID_SUCCESS",
  DELETE_CURRICULUM_BY_ID_FAILURE: "DELETE_CURRICULUM_BY_ID_FAILURE",

  ADD_CURRICULUM_REQUEST: "ADD_CURRICULUM_REQUEST",
  ADD_CURRICULUM_SUCCESS: "ADD_CURRICULUM_REQUEST",
  ADD_CURRICULUM_FAILURE: "ADD_CURRICULUM_FAILURE",

  UPDATE_CURRICULUMS_REQUEST: "UPDATE_CURRICULUMS_REQUEST",
  UPDATE_CURRICULUMS_SUCCESS: "UPDATE_CURRICULUMS_SUCCESS",
  UPDATE_CURRICULUMS_FAILURE: "UPDATE_CURRICULUMS_FAILURE",
};

export const authorConstants = {
  GET_ALL_AUTHORS_REQUEST: "GET_ALL_AUTHORS_REQUEST",
  GET_ALL_AUTHORS_SUCCESS: "GET_ALL_AUTHORS_SUCCESS",
  GET_ALL_AUTHORS_FAILURE: "GET_ALL_AUTHORS_FAILURE",

  GET_ALL_AUTHORS_PUBLISHED_REQUEST: "GET_ALL_AUTHORS_PUBLISHED_REQUEST",
  GET_ALL_AUTHORS_PUBLISHED_SUCCESS: "GET_ALL_AUTHORS_PUBLISHED_SUCCESS",
  GET_ALL_AUTHORS_PUBLISHED_FAILURE: "GET_ALL_AUTHORS_PUBLISHED_FAILURE",

  DELETE_AUTHOR_BY_ID_REQUEST: "DELETE_AUTHOR_BY_ID_REQUEST",
  DELETE_AUTHOR_BY_ID_SUCCESS: "DELETE_AUTHOR_BY_ID_SUCCESS",
  DELETE_AUTHOR_BY_ID_FAILURE: "DELETE_AUTHOR_BY_ID_FAILURE",

  ADD_AUTHOR_REQUEST: "ADD_AUTHOR_REQUEST",
  ADD_AUTHOR_SUCCESS: "ADD_AUTHOR_REQUEST",
  ADD_AUTHOR_FAILURE: "ADD_AUTHOR_FAILURE",

  UPDATE_AUTHOR_REQUEST: "UPDATE_AUTHOR_REQUEST",
  UPDATE_AUTHOR_SUCCESS: "UPDATE_AUTHOR_SUCCESS",
  UPDATE_AUTHOR_FAILURE: "UPDATE_AUTHOR_FAILURE",
};


export const blogConstants = {
  GET_ALL_BLOGS_REQUEST: "GET_ALL_BLOGS_REQUEST",
  GET_ALL_BLOGS_SUCCESS: "GET_ALL_BLOGS_SUCCESS",
  GET_ALL_BLOGS_FAILURE: "GET_ALL_BLOGS_FAILURE",

  GET_ALL_BLOGS_PUBLISHED_REQUEST: "GET_ALL_BLOGS_PUBLISHED_REQUEST",
  GET_ALL_BLOGS_PUBLISHED_SUCCESS: "GET_ALL_BLOGS_PUBLISHED_SUCCESS",
  GET_ALL_BLOGS_PUBLISHED_FAILURE: "GET_ALL_BLOGS_PUBLISHED_FAILURE",

  DELETE_BLOG_BY_ID_REQUEST: "DELETE_BLOG_BY_ID_REQUEST",
  DELETE_BLOG_BY_ID_SUCCESS: "DELETE_BLOG_BY_ID_SUCCESS",
  DELETE_BLOG_BY_ID_FAILURE: "DELETE_BLOG_BY_ID_FAILURE",

  ADD_BLOG_REQUEST: "ADD_BLOG_REQUEST",
  ADD_BLOG_SUCCESS: "ADD_BLOG_REQUEST",
  ADD_BLOG_FAILURE: "ADD_BLOG_FAILURE",

  UPDATE_BLOGS_REQUEST: "UPDATE_BLOGS_REQUEST",
  UPDATE_BLOGS_SUCCESS: "UPDATE_BLOGS_SUCCESS",
  UPDATE_BLOGS_FAILURE: "UPDATE_BLOGS_FAILURE",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};

export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};
